project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: labs.qmd
        text: Labs
      - href: https://hmc-e155.github.io/
        text: Resources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



