---
title: "Project Reflection 1"
description: "First Reflection on Project Work"
author: "Luke Summers"
date: "11/19/24"
categories:
  - reflection
draft: false
---
I have found my time spent working on the project to be greatly enjoyable so far. My main tasks have been programming the game logic and 3D printing the chess pieces. The 3D printing has been easy as I did not have to design the pieces myself, so it has just been loading them into a slicer and printing them. The pieces I chose were not typical chess pieces, and they bring me a small amount of enjoyment as I think they look funny. The game logic programming has been where most of my thinking has gone, as my partner has been handling the board construction and light programming. The light programming was the part of the project we were most worried about, as we are using an LED strip we found in our lab so there was uncertainty associated with it. The game logic programming has been enjoyable to me as I feel like it is the biggest crossover of my work in E155 and the rest of my work as a computer science major. I have enjoyed applying some of the concepts I have learned in my more software focused classes to this specific application of a program on an MCU. I am excited to finish up the game logic and start putting everything together, including the board, pieces, and interface with the FPGA/MCU.