---
title: "Week 3"
description: "Third week reflection"
author: "Luke Summers"
date: "9/20/24"
categories:
  - reflection
draft: false
---
In this week of E155 I have enjoyed having to face a different kind of debugging that debugging software cannot offer. In building my finite state machine for lab 3, I have found difficulty in even what I thought were the more simple tasks of the lab. In my first attempt to move from simulation to hardware for the lab, I found my modules that worked completely as expected in simulation not even show the slightest signs of working in hardware. Although it would have been nice to create a working design for the lab on the first try, I was excited at the opportunity this gave me. \ 
I feel like in comparing how I have been thinking trying to debug my ciruit for the lab and how I usually think when trying to debug code, I have only found how different the processes are. There is an obvious sense of debugging strategies being resitricted without simple tools such as print statements, and that the goal is to check for function not for a status of function. I have enjoyed so far how these restictions have forced me to restructure my strategies towards debugging.